# Generated by Django 3.2.6 on 2021-08-15 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsAddress',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_admin_id', models.CharField(max_length=32, unique=True)),
                ('country', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=12)),
                ('box', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=64)),
                ('postal_address', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutsGroup',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_admin_id', models.CharField(default='', max_length=32, null=True)),
                ('number', models.CharField(default='', max_length=32, null=True)),
                ('name', models.CharField(default='', max_length=32, null=True)),
                ('foundation', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('only_leaders', models.BooleanField(default=False)),
                ('show_members_improved', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=128, null=True)),
                ('website', models.CharField(default='', max_length=128, null=True)),
                ('info', models.CharField(default='', max_length=128, null=True)),
                ('group_type', models.CharField(default='', max_length=32, null=True)),
                ('public_registration', models.BooleanField(default=False)),
                ('addresses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='scouts_groups.scoutsaddress')),
                ('sub_groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='scouts_groups.scoutsgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutsGroupType',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutsLocation',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.CharField(max_length=64)),
                ('longitude', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutsSectionName',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutsSection',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='scouts_groups.scoutsgroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_name', to='scouts_groups.scoutssectionname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scoutsgroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgrouptype'),
        ),
        migrations.AddField(
            model_name='scoutsaddress',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='scouts_groups.scoutslocation'),
        ),
    ]
