# Generated by Django 3.2.6 on 2021-08-12 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scouts_auth', '0032_auto_20210812_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsGroup',
            fields=[
                ('scoutsauthgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scouts_auth.scoutsauthgroup')),
            ],
            bases=('scouts_auth.scoutsauthgroup',),
        ),
        migrations.CreateModel(
            name='ScoutsGroupType',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ScoutsSectionName',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutsSection',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scouts_groups.scoutssectionname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scoutsgroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgrouptype'),
        ),
        migrations.CreateModel(
            name='DefaultScoutsSectionName',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutssectionname')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgrouptype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
