# Generated by Django 3.2.6 on 2021-08-17 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoutsgroup',
            old_name='group_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='scoutssectionname',
            name='gender',
            field=models.CharField(choices=[('X', 'Other'), ('F', 'Female'), ('M', 'Male'), ('H', 'Mixed')], default='H', max_length=12),
        ),
        migrations.AlterField(
            model_name='scoutssection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgroup'),
        ),
        migrations.AlterField(
            model_name='scoutssection',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scouts_groups.scoutssectionname'),
        ),
        migrations.CreateModel(
            name='ScoutsDefaultSectionName',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scouts_groups.scoutssectionname')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgrouptype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
