# Generated by Django 3.2.6 on 2021-08-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoutssectionname',
            unique_together={('name', 'gender')},
        ),
    ]
