# Generated by Django 3.2.6 on 2021-08-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_groups', '0002_auto_20210817_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoutsdefaultsectionname',
            unique_together={('type', 'name')},
        ),
    ]
