# Generated by Django 3.2.6 on 2021-08-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_groups', '0002_alter_scoutssectionname_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutsgroup',
            options={'ordering': ['group_admin_id', 'number']},
        ),
        migrations.AddField(
            model_name='scoutsgrouptype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scouts_groups.scoutsgrouptype'),
        ),
    ]
