# Generated by Django 3.2.6 on 2021-08-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scouts_auth', '0006_auto_20210810_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsGroup',
            fields=[
                ('scoutsauthgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scouts_auth.scoutsauthgroup')),
            ],
            bases=('scouts_auth.scoutsauthgroup',),
        ),
    ]
