# Generated by Django 3.2.10 on 2022-01-05 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scouts_auth.inuits.models.fields.django_shorthand_model_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampVisum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['camp__sections__name__age_group'],
            },
        ),
        migrations.CreateModel(
            name='CampYearCategorySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=128)),
                ('index', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredIntegerField(default=0)),
                ('description', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CategorySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['category_set__camp_year__year'],
            },
        ),
        migrations.CreateModel(
            name='CategorySetPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(default='Verbond', max_length=32, unique=True)),
                ('priority', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True)),
                ('link', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True)),
                ('label', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True)),
                ('name', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=32)),
            ],
            options={
                'ordering': ['check_type'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True)),
                ('link', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True)),
                ('name', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='visums.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='checktype',
            constraint=models.UniqueConstraint(fields=('check_type',), name='unique_check_type'),
        ),
        migrations.AddField(
            model_name='check',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.checktype'),
        ),
        migrations.AddField(
            model_name='check',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='visums.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='categorysetpriority',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_owner'),
        ),
        migrations.AddConstraint(
            model_name='categorysetpriority',
            constraint=models.UniqueConstraint(fields=('priority',), name='unique_priority'),
        ),
        migrations.AddField(
            model_name='categoryset',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sets', to='visums.campyearcategoryset'),
        ),
        migrations.AddField(
            model_name='categoryset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visums_categoryset_created', to=settings.AUTH_USER_MODEL, verbose_name='Instance created by'),
        ),
        migrations.AddField(
            model_name='categoryset',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.scoutsgrouptype'),
        ),
        migrations.AddField(
            model_name='categoryset',
            name='priority',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visums.categorysetpriority'),
        ),
        migrations.AddField(
            model_name='categoryset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visums_categoryset_updated', to=settings.AUTH_USER_MODEL, verbose_name='Instance last update by'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='visums.categoryset'),
        ),
        migrations.AddField(
            model_name='campyearcategoryset',
            name='camp_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_year_category_set', to='camps.campyear'),
        ),
        migrations.AddField(
            model_name='campvisum',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.camp'),
        ),
        migrations.AddField(
            model_name='campvisum',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.categoryset'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='check',
            unique_together={('name', 'sub_category')},
        ),
        migrations.AddConstraint(
            model_name='categoryset',
            constraint=models.UniqueConstraint(fields=('category_set', 'group_type'), name='unique_set_for_category_set_and_group_type'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_set')},
        ),
    ]
