# Generated by Django 3.2.6 on 2021-08-30 08:47

from django.db import migrations, models
import django.db.models.deletion
import inuits.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampVisum',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampVisumCategory',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', inuits.models.UniqueRequiredCharField(max_length=128, unique=True)),
                ('index', inuits.models.RequiredIntegerField(default=0)),
                ('description', inuits.models.OptionalTextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CampVisumCategorySet',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['camp_year'],
            },
        ),
        migrations.CreateModel(
            name='CampVisumCategorySetPriority',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.CharField(default='Verbond', max_length=32, unique=True)),
                ('priority', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CampVisumConcern',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampVisumConcernType',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', inuits.models.RequiredCharField(max_length=32)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='CampVisumLinkedCategory',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='camps.camp')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_categories', to='visums.campvisumcategory')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visums.campvisumcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampVisumSubCategory',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', inuits.models.RequiredCharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='visums.campvisumcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampVisumLinkedSubCategory',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.campvisumlinkedcategory')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visums.campvisumsubcategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_sub_categories', to='visums.campvisumsubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampVisumLinkedConcern',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.campvisumconcern')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='visums.campvisumlinkedsubcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.campvisumconcerntype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='campvisumconcerntype',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_type'),
        ),
        migrations.AddField(
            model_name='campvisumconcern',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='visums.campvisumsubcategory'),
        ),
        migrations.AddField(
            model_name='campvisumconcern',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.campvisumconcerntype'),
        ),
        migrations.AddConstraint(
            model_name='campvisumcategorysetpriority',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_owner'),
        ),
        migrations.AddConstraint(
            model_name='campvisumcategorysetpriority',
            constraint=models.UniqueConstraint(fields=('priority',), name='unique_priority'),
        ),
        migrations.AddField(
            model_name='campvisumcategoryset',
            name='camp_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.campyear'),
        ),
        migrations.AddField(
            model_name='campvisumcategoryset',
            name='categories',
            field=models.ManyToManyField(to='visums.CampVisumCategory'),
        ),
        migrations.AddField(
            model_name='campvisumcategoryset',
            name='priority',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visums.campvisumcategorysetpriority'),
        ),
        migrations.AddField(
            model_name='campvisumcategoryset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grouptype'),
        ),
        migrations.AddField(
            model_name='campvisum',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visum', to='camps.camp'),
        ),
        migrations.AddField(
            model_name='campvisum',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.campvisumcategoryset'),
        ),
        migrations.AlterUniqueTogether(
            name='campvisumsubcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddConstraint(
            model_name='campvisumconcern',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AlterUniqueTogether(
            name='campvisumconcern',
            unique_together={('name', 'sub_category')},
        ),
    ]
