# Generated by Django 4.1.5 on 2023-02-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedcheck',
            options={'ordering': ['parent__index'], 'permissions': (('view_campvisum_member_data', 'User is allowed to view gdpr-sensitive data of members'),)},
        ),
    ]
