# Generated by Django 3.2.10 on 2022-01-06 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='visums.linkedcategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.check')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.linkedsubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedCategorySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.categoryset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='linkedcategory',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='visums.linkedcategoryset'),
        ),
        migrations.AddField(
            model_name='linkedcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.category'),
        ),
        migrations.AlterField(
            model_name='campvisum',
            name='category_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visums.linkedcategoryset'),
        ),
    ]
