# Generated by Django 3.2.10 on 2022-01-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedfileuploadcheck',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scouts_auth.persistedfile'),
        ),
    ]
