# Generated by Django 3.2.10 on 2022-01-10 17:32

from django.db import migrations, models
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedlocationcheck',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedlocationcheck',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedlocationcheck',
            name='zoom',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalIntegerField(blank=True, null=True),
        ),
    ]
