# Generated by Django 3.2.16 on 2023-01-18 15:14

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'permissions': [('view_camp_locations', 'User can view all camp locations'), ('view_visum', 'User can view a camp visum'), ('edit_visum', 'User can create and edit a camp visum'), ('delete_visum', 'User can delete a camp visum'), ('list_visum', 'User can list visums for his/her group'), ('view_visum_notes', 'User is a DC and can view approval notes'), ('edit_visum_notes', 'User is a DC and can edit approval notes'), ('view_member_data', 'User is allowed to view gdpr-sensitive member data')]},
        ),
        migrations.AddField(
            model_name='check',
            name='requires_permission',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=128),
        ),
    ]
