# Generated by Django 3.2.6 on 2021-08-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'ordering': ['camp__sections__age_group']},
        ),
        migrations.RemoveField(
            model_name='campvisumlinkedconcern',
            name='type',
        ),
        migrations.AlterField(
            model_name='campvisum',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.camp'),
        ),
    ]
