# Generated by Django 3.2.10 on 2022-01-07 13:18

from django.db import migrations, models
import django.db.models.deletion
import scouts_auth.inuits.models.fields.datetype_aware_date_field
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedcontactcheck',
            name='value',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='linkeddatecheck',
            name='value',
            field=scouts_auth.inuits.models.fields.datetype_aware_date_field.DatetypeAwareDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddurationcheck',
            name='end_date',
            field=scouts_auth.inuits.models.fields.datetype_aware_date_field.DatetypeAwareDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddurationcheck',
            name='start_date',
            field=scouts_auth.inuits.models.fields.datetype_aware_date_field.DatetypeAwareDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedfileuploadcheck',
            name='value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scouts_auth.persistedfile'),
        ),
        migrations.AlterField(
            model_name='linkedinputcheck',
            name='value',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='linkedlocationcheck',
            name='value',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='linkedlocationcontactcheck',
            name='value',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='linkedmembercheck',
            name='value',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, max_length=64),
        ),
    ]
