# Generated by Django 4.1.5 on 2023-02-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'permissions': [('read_camp_locations', 'User can view all camp locations'), ('read_member_data', 'User is allowed to view gdpr-sensitive member data'), ('read_campvisum_notes', 'User is a DC and can view approval notes'), ('update_campvisum_notes', 'User is a DC and can edit approval notes')]},
        ),
        migrations.AlterModelOptions(
            name='linkedsubcategory',
            options={'ordering': ['parent__index'], 'permissions': [('view_campvisum_feedback', "User can view the DC's feedback"), ('change_campvisum_feedback', 'User is a DC and can edit the feedback'), ('view_campvisum_approval', 'User can view approval status'), ('change_campvisum_approval', 'User is a DC and can set approval status')]},
        ),
    ]
