# Generated by Django 4.1.5 on 2023-02-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'ordering': ['sections__age_group'], 'permissions': [('view_campvisum_locations', 'User can view all camp locations'), ('view_campvisum_notes', 'User is a DC and can view approval notes'), ('change_campvisum_notes', 'User is a DC and can edit approval notes')]},
        ),
    ]
