# Generated by Django 3.2.10 on 2022-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
        ('visums', '0002_alter_linkedfileuploadcheck_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedfileuploadcheck',
            name='value',
        ),
        migrations.AddField(
            model_name='linkedfileuploadcheck',
            name='value',
            field=models.ManyToManyField(to='scouts_auth.PersistedFile'),
        ),
    ]
