# Generated by Django 3.2.12 on 2022-03-23 14:42

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0002_auto_20220323_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='validators',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=128),
        ),
    ]
