# Generated by Django 3.2.10 on 2022-01-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0002_auto_20220106_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedcheck',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='visums.linkedsubcategory'),
        ),
    ]
