# Generated by Django 4.1.5 on 2023-02-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0002_alter_campvisum_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'ordering': ['sections__age_group'], 'permissions': [('view_campvisum_locations', 'User can view all camp locations'), ('view_campvisum_member_data', 'User is allowed to view gdpr-sensitive data of members'), ('view_campvisum_notes', 'User is a DC and can view approval notes'), ('change_campvisum_notes', 'User is a DC and can edit approval notes')]},
        ),
        migrations.AlterModelOptions(
            name='linkedcheck',
            options={'ordering': ['parent__index']},
        ),
    ]
