# Generated by Django 4.1.5 on 2023-01-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0003_alter_campvisum_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'permissions': [('create_visum', 'User can create  a camp visum'), ('read_visum', 'User can view a camp visum'), ('update_visum', 'User can edit a camp visum'), ('delete_visum', 'User can delete a camp visum'), ('list_visum', 'User can list visums for his/her group'), ('read_camp_locations', 'User can view all camp locations'), ('read_member_data', 'User is allowed to view gdpr-sensitive member data'), ('read_visum_notes', 'User is a DC and can view approval notes'), ('update_visum_notes', 'User is a DC and can edit approval notes')]},
        ),
        migrations.AlterModelOptions(
            name='linkedsubcategory',
            options={'ordering': ['parent__index'], 'permissions': [('read_visum_feedback', "User can view the DC's feedback"), ('update_visum_feedback', 'User is a DC and can edit the feedback'), ('read_visum_approval', 'User can view approval status'), ('update_visum_approval', 'User is a DC and can set approval status')]},
        ),
    ]
