# Generated by Django 3.2.12 on 2022-03-23 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visums', '0003_check_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campvisumapproval',
            name='district_commissioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campvisumapproval_district_commissioner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campvisumapproval',
            name='group_leaders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campvisumapproval_group_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campvisumapproval',
            name='leaders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campvisumapproval_leaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
