# Generated by Django 4.1.5 on 2023-02-08 21:05

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0003_alter_campvisum_options_alter_linkedcheck_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'ordering': ['sections__age_group', 'name'], 'permissions': [('view_campvisum_locations', 'User can view all camp locations'), ('view_campvisum_member_data', 'User is allowed to view gdpr-sensitive data of members'), ('view_campvisum_notes', 'User is a DC and can view approval notes'), ('change_campvisum_notes', 'User is a DC and can edit approval notes')]},
        ),
        migrations.AddField(
            model_name='campvisum',
            name='group_name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
