# Generated by Django 4.1.5 on 2023-01-26 10:32

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0004_alter_campvisum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='linked_to',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=128),
        ),
    ]
