# Generated by Django 3.2.12 on 2022-03-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0004_auto_20220323_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'ordering': ['camp__sections__age_group']},
        ),
    ]
