# Generated by Django 3.2.12 on 2022-03-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0005_alter_campvisum_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'ordering': ['camp__sections__age_group'], 'permissions': [('create_campvisum', 'User can create a camp')]},
        ),
    ]
