# Generated by Django 3.2.12 on 2022-04-06 09:21

from django.db import migrations, models
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0007_auto_20220402_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvisum',
            options={'permissions': [('create_campvisum', 'User can create a camp')]},
        ),
        migrations.AddField(
            model_name='campvisum',
            name='camp_registration_mail_last_sent',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campvisum',
            name='camp_registration_mail_sent_after_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
