# Generated by Django 3.2.12 on 2022-04-06 09:25

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0008_auto_20220406_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campvisum',
            name='camp_registration_mail_last_sent',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalDateTimeField(blank=True, null=True),
        ),
    ]
