# Generated by Django 3.2.12 on 2022-04-07 15:01

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0009_alter_campvisum_camp_registration_mail_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campvisum',
            name='state',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('DATA_REQUIRED', 'data_required'), ('SIGNABLE', 'signable'), ('REVIEWABLE', 'reviewable'), ('REVIEWED_APPROVED', 'reviewed_approved'), ('REVIEWED_FEEDBACK', 'reviewed_feedback'), ('REVIEWED_DISAPPROVED', 'reviewed_disapproved'), ('FEEDBACK_HANDLED', 'feedback_handled')], default='DATA_REQUIRED', max_length=32),
        ),
    ]
