# Generated by Django 3.2.12 on 2022-04-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0008_alter_campvisum_options'),
        ('visums', '0010_campvisum_state'),
    ]

    operations = [
    ]
