# Generated by Django 3.2.12 on 2022-04-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0012_auto_20220408_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedsubcategory',
            options={'ordering': ['parent__index'], 'permissions': [('view_visum_feedback', "User can view the DC's feedback"), ('edit_visum_feedback', 'User is a DC and can edit the feedback')]},
        ),
    ]
