# Generated by Django 3.2.12 on 2022-04-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0014_linkedcategory_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedcategory',
            options={'ordering': ['parent__index'], 'permissions': [('view_visum_notes', 'User is a DC and can view approval notes'), ('edit_visum_notes', 'User is a DC and can edit approval notes')]},
        ),
        migrations.AlterModelOptions(
            name='linkedsubcategory',
            options={'ordering': ['parent__index'], 'permissions': [('view_visum_feedback', "User can view the DC's feedback"), ('edit_visum_feedback', 'User is a DC and can edit the feedback'), ('view_visum_approval', 'User can view approval status'), ('edit_visum_approval', 'User is a DC and can set approval status')]},
        ),
        migrations.RemoveField(
            model_name='campvisum',
            name='approval',
        ),
    ]
