# Generated by Django 3.2.12 on 2022-04-27 15:15

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0017_auto_20220419_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campvisum',
            name='state',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('DATA_REQUIRED', 'data_required'), ('SIGNABLE', 'signable'), ('NOT_SIGNABLE', 'not_signable'), ('REVIEWABLE', 'reviewable'), ('REVIEWED_APPROVED', 'reviewed_approved'), ('REVIEWED_FEEDBACK', 'reviewed_feedback'), ('REVIEWED_DISAPPROVED', 'reviewed_disapproved'), ('FEEDBACK_HANDLED', 'feedback_handled')], default='DATA_REQUIRED', max_length=32),
        ),
        migrations.AlterField(
            model_name='linkedsubcategory',
            name='approval',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('U', 'UNDECIDED'), ('A', 'APPROVED'), ('N', 'APPROVED_WITH_FEEDBACK'), ('D', 'DISAPPROVED'), ('F', 'FEEDBACK_RESOLVED')], default='U', max_length=1),
        ),
    ]
