# Generated by Django 3.2.12 on 2022-04-28 17:00

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0019_alter_campvisum_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedsubcategory',
            name='approval',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('U', 'UNDECIDED'), ('A', 'APPROVED'), ('N', 'APPROVED_WITH_FEEDBACK'), ('D', 'DISAPPROVED'), ('F', 'FEEDBACK_RESOLVED'), ('R', 'FEEDBACK_READ')], default='U', max_length=1),
        ),
    ]
