# Generated by Django 3.2.12 on 2022-05-06 09:23

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0020_alter_linkedsubcategory_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campvisum',
            name='notes',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='linkedsubcategory',
            name='feedback',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=300),
        ),
    ]
