# Generated by Django 3.2.14 on 2022-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('visums', '0023_alter_campvisum_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedlocationcheck',
            name='locations',
            field=models.ManyToManyField(related_name='checks', to='locations.LinkedLocation'),
        ),
    ]
