# Generated by Django 3.2.10 on 2022-02-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultdeadline',
            unique_together={('name', 'deadline_type')},
        ),
    ]
