# Generated by Django 3.2.12 on 2022-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_linkeddeadlineitem_linked_deadline_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='is_camp_registration',
            field=models.BooleanField(default=False),
        ),
    ]
