# Generated by Django 3.2.12 on 2022-04-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_linkeddeadlineitem_linked_deadline_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkeddeadline',
            name='items',
        ),
        migrations.AddField(
            model_name='linkeddeadlineitem',
            name='linked_deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deadlines.linkeddeadline'),
        ),
    ]
