# Generated by Django 3.2.12 on 2022-04-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0004_auto_20220413_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkeddeadlineitem',
            name='flag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadline_item', to='deadlines.linkeddeadlineflag'),
        ),
    ]
