# Generated by Django 3.2.12 on 2022-04-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0005_alter_linkeddeadlineitem_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkeddeadlineitem',
            name='linked_deadline_fix',
        ),
    ]
