# Generated by Django 4.1.5 on 2023-02-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camptype',
            options={'ordering': ['index', 'camp_type'], 'permissions': [('list_camptype', 'User can list visums for his/her group')]},
        ),
    ]
