# Generated by Django 4.1.5 on 2023-02-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_alter_camptype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camptype',
            options={'ordering': ['index', 'camp_type']},
        ),
    ]
