# Generated by Django 3.2.16 on 2022-12-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scoutsfunction',
            name='unique_user_for_function',
        ),
        migrations.RenameField(
            model_name='scoutsfunction',
            old_name='scouts_groups',
            new_name='_scouts_groups',
        ),
        migrations.RenameField(
            model_name='scoutsfunction',
            old_name='user',
            new_name='_user',
        ),
        migrations.RenameField(
            model_name='scoutsuser',
            old_name='persisted_scouts_groups',
            new_name='_persisted_scouts_groups',
        ),
        migrations.AddConstraint(
            model_name='scoutsfunction',
            constraint=models.UniqueConstraint(fields=('_user', 'group_admin_id'), name='unique_user_for_function'),
        ),
    ]
