# Generated by Django 3.2.12 on 2022-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutsgroup',
            options={'ordering': ['number']},
        ),
    ]
