# Generated by Django 4.1.5 on 2023-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persistedfile',
            options={'ordering': ['original_name']},
        ),
        migrations.AddIndex(
            model_name='persistedfile',
            index=models.Index(fields=['original_name'], name='original_name_idx'),
        ),
    ]
