# Generated by Django 3.2.14 on 2022-12-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoutsfunction',
            old_name='scouts_groups',
            new_name='_scouts_groups',
        ),
        migrations.RenameField(
            model_name='scoutsuser',
            old_name='persisted_scouts_groups',
            new_name='_persisted_scouts_groups',
        ),
    ]
