# Generated by Django 4.1.5 on 2023-02-10 19:03

from django.db import migrations, models
import scouts_auth.inuits.models.fields.django_shorthand_model_fields
import scouts_auth.inuits.models.fields.timezone_aware_date_time_field


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsUserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=128)),
                ('expiration', scouts_auth.inuits.models.fields.timezone_aware_date_time_field.TimezoneAwareDateTimeField()),
                ('data', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalTextField(blank=True, default='')),
            ],
        ),
    ]
