# Generated by Django 3.2.16 on 2023-01-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0002_auto_20221220_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutsgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scouts_auth.scoutsgroup', verbose_name='Parent group'),
        ),
    ]
