# Generated by Django 3.2.12 on 2022-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0002_alter_scoutsgroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutsfunction',
            name='group',
        ),
        migrations.AddField(
            model_name='scoutsfunction',
            name='scouts_groups',
            field=models.ManyToManyField(to='scouts_auth.ScoutsGroup'),
        ),
    ]
