# Generated by Django 4.1.5 on 2023-03-02 15:07

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0002_alter_scoutsusersession_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistedfile',
            name='directory_path',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(default='', max_length=128),
        ),
    ]
