# Generated by Django 3.2.16 on 2022-12-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0002_auto_20221215_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoutsfunction',
            old_name='user',
            new_name='_user',
        ),
    ]
