# Generated by Django 3.2.12 on 2022-03-28 14:19

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0003_auto_20220328_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutsfunction',
            name='name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=128),
        ),
    ]
