# Generated by Django 4.1.5 on 2023-05-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0003_persistedfile_directory_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistedfile',
            name='directory_path',
        ),
    ]
