# Generated by Django 3.2.16 on 2023-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0003_scoutsgroup_parent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutsgroup',
            name='parent_group',
        ),
        migrations.AddField(
            model_name='scoutsgroup',
            name='_child_groups',
            field=models.ManyToManyField(blank=True, to='scouts_auth.ScoutsGroup', verbose_name='Child groups'),
        ),
    ]
