# Generated by Django 3.2.16 on 2022-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0003_rename_user_scoutsfunction__user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scoutsfunction',
            name='unique_user_for_function',
        ),
        migrations.AddConstraint(
            model_name='scoutsfunction',
            constraint=models.UniqueConstraint(fields=('_user', 'group_admin_id'), name='unique_user_for_function'),
        ),
    ]
