# Generated by Django 4.1.5 on 2023-01-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0005_alter_persistedfile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutsuser',
            options={'permissions': [('access_disabled_entities', 'Access disabled entities')]},
        ),
    ]
