# Generated by Django 3.2.12 on 2022-05-10 10:15

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0005_scoutsgroup_parent_group_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutsgroup',
            name='parent_group_admin_id',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
