# Generated by Django 3.2.12 on 2022-05-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_auth', '0006_alter_scoutsgroup_parent_group_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutsuser',
            name='persisted_scouts_functions',
        ),
        migrations.AddField(
            model_name='scoutsfunction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persisted_scouts_functions', to=settings.AUTH_USER_MODEL),
        ),
    ]
