# Generated by Django 3.2.6 on 2021-08-24 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inuits.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scouts_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutsCamp',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('start_date', inuits.models.OptionalDateField(blank=True, null=True)),
                ('end_date', inuits.models.OptionalDateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouts_camps_scoutscamp_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('sections', models.ManyToManyField(to='scouts_groups.ScoutsSection')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
