# Generated by Django 3.2.6 on 2021-08-10 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4df4f324-6739-400f-9f02-e4c4ca3012b8'), editable=False),
        ),
    ]
