# Generated by Django 3.2.6 on 2021-08-10 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b358c4e3-f6da-427d-933d-48d57a698601'), editable=False),
        ),
    ]
