# Generated by Django 3.2.6 on 2021-08-09 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d7d1fc97-1363-4a4d-bfa6-b989cfaeb95e'), editable=False),
        ),
    ]
