# Generated by Django 3.2.6 on 2021-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_groups', '0003_auto_20210818_1725'),
        ('scouts_camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutscamp',
            name='sections',
            field=models.ManyToManyField(to='scouts_groups.ScoutsSection'),
        ),
        migrations.AlterField(
            model_name='scoutscamp',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='scoutscamp',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
