# Generated by Django 3.2.6 on 2021-08-20 08:59

from django.db import migrations
import inuits.models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts_camps', '0002_auto_20210819_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutscamp',
            name='end_date',
            field=inuits.models.OptionalDateField(),
        ),
        migrations.AlterField(
            model_name='scoutscamp',
            name='start_date',
            field=inuits.models.OptionalDateField(),
        ),
    ]
