from .camp_location_serializer import CampLocationSerializer
from .camp_location_minimal_serializer import CampLocationMinimalSerializer

from .linked_location_serializer import LinkedLocationSerializer
