# Generated by Django 4.1.5 on 2023-01-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutssection',
            options={'ordering': ['age_group'], 'permissions': [('create_section', 'User can create a group section'), ('read_section', 'User can view a group section'), ('update_section', 'User can edit a group section'), ('delete_section', 'User can delete a group section'), ('list_section', 'User can list sections for his/her group')]},
        ),
    ]
