# Generated by Django 3.2.10 on 2022-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scoutssection',
            name='unique_section_group_admin_id',
        ),
        migrations.AddConstraint(
            model_name='scoutssection',
            constraint=models.UniqueConstraint(fields=('group_admin_id', 'name'), name='unique_section_group_admin_id_and_name'),
        ),
    ]
