# Generated by Django 3.2.11 on 2022-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoutssectionname',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scoutssectionname',
            constraint=models.UniqueConstraint(fields=('name', 'gender', 'age_group'), name='unique_name_gender_and_age_group'),
        ),
    ]
