# Generated by Django 3.2.11 on 2022-02-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutssection',
            name='group_type',
        ),
    ]
