# Generated by Django 3.2.12 on 2022-03-21 14:44

from django.db import migrations, models
import django.db.models.deletion
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutssection',
            options={'ordering': ['age_group']},
        ),
        migrations.RemoveConstraint(
            model_name='scoutssection',
            name='unique_group_and_name_for_section',
        ),
        migrations.AddField(
            model_name='scoutssection',
            name='age_group',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scoutssection',
            name='gender',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('F', 'Female'), ('I', 'Mixed'), ('M', 'Male'), ('X', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='scoutssection',
            name='section_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.scoutssectionname'),
        ),
        migrations.AlterField(
            model_name='scoutssection',
            name='name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='scoutssection',
            constraint=models.UniqueConstraint(fields=('group', 'name', 'gender', 'age_group'), name='unique_group_name_gender_age_group_for_section'),
        ),
    ]
