# Generated by Django 3.2.12 on 2022-03-21 16:28

from django.db import migrations, models
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_scoutssection_section_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='defaultscoutssectionname',
            name='unique_group_type_and_name_for_default_scouts_section_name',
        ),
        migrations.AddField(
            model_name='defaultscoutssectionname',
            name='age_group',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='defaultscoutssectionname',
            name='gender',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.DefaultCharField(blank=True, choices=[('F', 'Female'), ('I', 'Mixed'), ('M', 'Male'), ('X', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='defaultscoutssectionname',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultscoutssectionname',
            name='name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(default='none', max_length=128),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='defaultscoutssectionname',
            constraint=models.UniqueConstraint(fields=('group_type', 'name', 'gender', 'age_group'), name='unique_group_type_and_name_gender_age_group_for_default_scouts_section_name'),
        ),
    ]
