# Generated by Django 3.2.12 on 2022-03-21 17:56

from django.db import migrations
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20220321_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultscoutssectionname',
            name='name',
            field=scouts_auth.inuits.models.fields.django_shorthand_model_fields.RequiredCharField(default='', max_length=128),
        ),
    ]
