# Generated by Django 3.2.16 on 2023-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20230105_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedlocation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='linkedlocation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
