# Generated by Django 3.2.10 on 2022-01-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_camplocation_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camplocation',
            name='zoom',
        ),
    ]
