# Generated by Django 3.2.16 on 2023-01-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20230109_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedlocation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedlocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
