# Generated by Django 3.2.10 on 2022-01-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inuitsnonmember',
            old_name='group_admin_id',
            new_name='group_group_admin_id',
        ),
    ]
